CREATE DATABASE IF NOT EXISTS DB202DWESProyectoTema4;
USE DB202DWESProyectoTema4;
CREATE USER IF NOT EXISTS 'user202DWESProyectoTema4'@'%' IDENTIFIED BY 'paso';
GRANT ALL PRIVILEGES ON DB202DWESProyectoTema4.* TO 'user202DWESProyectoTema4'@'%';
CREATE TABLE IF NOT EXISTS T02_Departamento(
T02_CodDepartamento CHAR(3) PRIMARY KEY,
T02_DescDepartamento VARCHAR(255) DEFAULT NULL,
T02_FechaCreacionDepartamento DATETIME DEFAULT CURRENT_TIMESTAMP,
T02_VolumenDeNegocio FLOAT DEFAULT NULL,
T02_FechaBajaDepartamento DATETIME DEFAULT NULL)ENGINE=InnoDB;